from __future__ import annotations

EMPTY = 0
BLACK = 1
WHITE = 2

PLAYER_BLACK = "black"
PLAYER_WHITE = "white"
PLAYER_NONE = "none"

DEFAULT_BOARD_SIZE = 15
DEFAULT_SERVER_PORT = 8888
DEFAULT_HTTP_PORT = 8080
DEFAULT_SERVER_HOST = "0.0.0.0"

MAX_PLAYERS_PER_ROOM = 2

MSG_JOIN_ROOM = "join_room"
MSG_ROOM_JOINED = "room_joined"
MSG_ROOM_FULL = "room_full"
MSG_GAME_START = "game_start"
MSG_MOVE = "move"
MSG_MOVE_RESULT = "move_result"
MSG_INVALID_MOVE = "invalid_move"
MSG_GAME_OVER = "game_over"
MSG_DRAW = "draw"
MSG_RESTART_REQUEST = "restart_request"
MSG_RESTART_RESPONSE = "restart_response"
MSG_GAME_RESTART = "game_restart"
MSG_PLAYER_LEFT = "player_left"
MSG_ERROR = "error"
MSG_PING = "ping"
MSG_PONG = "pong"

RESULT_WIN_BLACK = "win_black"
RESULT_WIN_WHITE = "win_white"
RESULT_DRAW = "draw"
RESULT_ONGOING = "ongoing"

ERR_SERVER_CONNECTION_FAILED = "SERVER_CONNECTION_FAILED"
ERR_SERVER_DISCONNECTED = "SERVER_DISCONNECTED"
ERR_ROOM_NOT_FOUND = "ROOM_NOT_FOUND"
ERR_ROOM_FULL = "ROOM_FULL"
ERR_NETWORK_ERROR = "NETWORK_ERROR"
ERR_INVALID_COORDINATE = "INVALID_COORDINATE"
ERR_DUPLICATE_MOVE = "DUPLICATE_MOVE"
ERR_NOT_YOUR_TURN = "NOT_YOUR_TURN"
ERR_GAME_ENDED = "GAME_ENDED"
ERR_INVALID_JSON = "INVALID_JSON"
